notes/urls.py
from django.contrib import admin
from django.urls import path
from notes.views import My_notes, NotesFormView, get_topic_list, delete_topic

urlpatterns = [
    path('list', My_notes),
    path('form', NotesFormView.as_view()),
    path('notes_list/', get_topic_list),
    path('delete/', delete_topic),
]

notes_app/urls.py
from django.contrib import admin
from django.urls import path, include
from notes.forms import *
from notes.views import NotesFormView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('notes/', include('notes.urls')),
    path('notes/form', NotesFormView.as_view())
]

notes/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _


class Profile(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=50)
    birth_date = models.DateField(null=True, blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user_profile')


# Create your models here.

class Notes(models.Model):
    TOPIC_TYPES = [
        (1, 'Важные срочные'),
        (2, 'Важные не срочные'),
        (3, 'Неважные срочные'),
        (4, 'Неважные не срочные'),
    ]
    title = models.CharField(max_length=50)
    text = models.TextField(max_length=1500)
    reminder = models.DateTimeField(null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author')
    type = models.IntegerField(choices=TOPIC_TYPES)

    class Meta:
        verbose_name = _("Notes")
        verbose_name_plural = _("Notes")

notes/forms.py
from django import forms
from notes.models import Notes


class NotesForm(forms.ModelForm):
    class Meta:
        model = Notes
        exclude = ('reminder',)

notes/views.py
from django.http import HttpResponse, HttpResponseRedirect

from django.shortcuts import render, redirect
from django.views.generic import FormView

from notes.models import Notes
from notes.forms import NotesForm


def My_notes(request):
    my_notes = Notes.objects.filter(author_id=request.user.id)
    context = {'my2': my_notes}
    return render(request, 'profile.html', context)


def get_topic_list(request):
    topic_type = request.GET.get('type', None)
    if topic_type:
        queryset = Notes.objects.filter(type=topic_type, author_id=request.user.id)
    else:
        queryset = Notes.objects.filter(author_id=request.user.id)
    context = {'my2': queryset}
    return render(request, 'profile.html', context)


def create_notes_form(request):
    if request.method == 'POST':
        print(request.POST.get("title"))
        form = NotesForm(request.POST)
        if form.is_valid():
            # Topic.objects.create(**form.cleaned_data)
            return redirect('my2')
    else:
        form = NotesForm()
        return render(request, 'form.html', {'form': form})


def delete_topic(request):
    # I
    my_id = request.GET.get('my_id', None)
    topic = Notes.objects.get(id=my_id)
    topic.delete()
    # II
    # Topic.objects.filter(id=4).delete()
    return render(request, 'profile.html', {'my2': Notes.objects.filter(author_id=request.user.id)})


class NotesFormView(FormView):
    template_name = 'form.html'
    form_class = NotesForm
    success_url = 'list'

    def form_valid(self, form):
        Notes.objects.create(**form.cleaned_data)
        return HttpResponseRedirect(self.get_success_url())

# def index(request):
#     return HttpResponse("Hello from Notes app")

notes_app/templates/autoriz.html
<!DOCTYPE html>
<html>
  <head>
    <title>To Do List - Авторизация</title>
    <link rel="stylesheet" type="text/css" href="css/styles.css"> 
    <link rel="stylesheet" type="text/css" href="css/style.css">
  </head>
  <body>
    <h1>To Do List - Авторизация</h1>
    <div id="login-form">
      <form action="login.php" method="post">
        <label for="username">Имя пользователя:</label>
        <input type="text" id="username" name="username" required>
        <label for="password">Пароль:</label>
        <input type="password" id="password" name="password" required>
        <button type="submit">Войти</button>
      </form>
    </div>
  </body>
</html>

notes_app/templates/form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <div class="container">
    <form class="my_form" method="post" action="form">
    {% csrf_token %}
    {{ form.as_p }}



			<input type="submit" value="Добавить">
		</form>
    </div>
</body>
</html>

notes_app/templates/profile.html
{% load static %}

<!DOCTYPE html>

<html>
<head>
	<title>Моя записная книжка</title>

    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
	<div class="container">
		<br>
        <br>
        <br>
        <a class="form" href="/notes/form">Создать новую задачу</a>
                <ul class="menu">
					<li><a href="/notes/notes_list">All</a></li>
					<li><a href="/notes/notes_list?type=1">Важные срочные</a></li>
					<li><a href="/notes/notes_list?type=2">Важные не срочные</a></li>
					<li><a href="/notes/notes_list?type=3">Неважные срочные</a></li>
                    <li><a href="/notes/notes_list?type=4">Неважные не срочные</a></li>
				</ul>
  

		<h2>Записи</h2>
        <ul>
            {% for i in my2 %}
                <li>
                    <h3>{{ i.title }}</h3>
                    <p>{{ i.text }}</p>
                    {% if i.reminder %}
                         <p>Выполнить до: {{ i.reminder }}</p>
                    {% endif %}


                    <p>{{ i.get_type_display }}</p>

                    <div class="actions">

                        <a class="form" href="/notes/delete?my_id={{ i.id }}">Удалить</a>

                    </div>

                </li>
            {% endfor %}

        </ul>


	</div>
</body>
</html>